in:
  type: mysql_binlog
  host: localhost
  port: 3306
  database: test
  table: test
  user: root
  password: root
  from_binlog_filename: mysql-bin.000001
  from_binlog_position: 4
  enable_metadata: true
  metadata_prefix: _trocco
  columns:
    - {name: id, type: long}
    - {name: name, type: string}

out:
  type: stdout
