in:
  type: mysql_binlog
  host: localhost 
  port: 3306
  database: test
  table: name
  user: root
  password: root
  binlog_filename: mysql-binlog.00001
  binlog_position: 4
  enable_metadata: true
  metadata_prefix: _trocco
  columns:
    - {name: id, type: long}
    - {name: name, type: string}

out:
  type: stdout
